let e = {
  "5dc08a30-e79a-11e9-bb09-cd860116bbdb": {
    "season": "1",
    "number": "1",
    "date": "15 Jul. 2016",
    "title": "Chapter One: The Vanishing of Will Byers",
    "description": "At the U.S. Dept. of Energy an unexplained event occurs. Then when a young Dungeons and Dragons playing boy named Will disappears after a night with his friends, his mother Joyce and the town of Hawkins are plunged into darkness.",
    "rating": "8.6"
  },
  "5ec83630-e79a-11e9-bb09-cd860116bbdb": {
    "season": "1",
    "number": "2",
    "date": "15 Jul. 2016",
    "title": "Chapter Two: The Weirdo on Maple Street",
    "description": "Mike hides the mysterious girl in his house. Joyce gets a strange phone call.",
    "rating": "8.5"
  },
  "5ec83631-e79a-11e9-bb09-cd860116bbdb": {
    "season": "1",
    "number": "3",
    "date": "15 Jul. 2016",
    "title": "Chapter Three: Holly, Jolly",
    "description": "An increasingly concerned Nancy looks for Barb and finds out what Jonathan's been up to. Joyce is convinced Will is trying to talk to her.",
    "rating": "8.9"
  },
  "5ec83632-e79a-11e9-bb09-cd860116bbdb": {
    "season": "1",
    "number": "4",
    "date": "15 Jul. 2016",
    "title": "Chapter Four: The Body",
    "description": "Refusing to believe Will is dead, Joyce tries to connect with her son. The boys give Eleven a makeover. Jonathan and Nancy form an unlikely alliance.",
    "rating": "9.0"
  },
  "5ec83633-e79a-11e9-bb09-cd860116bbdb": {
    "season": "1",
    "number": "5",
    "date": "15 Jul. 2016",
    "title": "Chapter Five: The Flea and the Acrobat",
    "description": "Hopper breaks into the lab to find the truth about Will's death. The boys try to locate the \"gate\" that will take them to Will.",
    "rating": "8.8"
  },
  "60b734f0-e79a-11e9-bb09-cd860116bbdb": {
    "season": "1",
    "number": "1",
    "date": "4 Oct. 1995",
    "title": "Shito, Shuurai",
    "description": "Shinji Ikari, a 14-year-old boy in the city of Tokyo-3, is delivered to the secret organization NERV, where he is requested by his enigmatic father to save the city from an invading creature called an Angel.",
    "rating": "7.8"
  },
  "626d4960-e79a-11e9-bb09-cd860116bbdb": {
    "season": "1",
    "number": "2",
    "date": "11 Oct. 1995",
    "title": "Mishiranu, Tenjou",
    "description": "In the wake of the previous battle, Misato hastily decides to let Shinji have a room in her apartment, where he discovers just what an irresponsible person his new guardian is. Shinji is also haunted by memories of his fight with the Angel.",
    "rating": "8.1"
  },
  "626d4961-e79a-11e9-bb09-cd860116bbdb": {
    "season": "1",
    "number": "3",
    "date": "18 Oct. 1995",
    "title": "Naranai, Denwa",
    "description": "Shinji transfers into a new school within Tokyo-3, catching the fascination of his classmates - and igniting the ire of one student whose sister was injured in the EVA's last battle. Meanwhile, a second Angel makes its way into the city.",
    "rating": "7.8"
  },
  "626d4962-e79a-11e9-bb09-cd860116bbdb": {
    "season": "1",
    "number": "4",
    "date": "25 Oct. 1995",
    "title": "Ame, Nigedashita Ato",
    "description": "Frustrated by his newfound responsibilities, Shinji runs away from Misato and NERV. After being escorted back to the organization by armed officials, Shinji must decide whether he truly wants to abandon his role as a pilot.",
    "rating": "7.6"
  },
  "626d4963-e79a-11e9-bb09-cd860116bbdb": {
    "season": "1",
    "number": "5",
    "date": "1 Nov. 1995",
    "title": "Rei, Kokoro no Mukou ni",
    "description": "Rei Ayanami, the pilot of Evangelion Unit 00, is scheduled to undergo another activation test following a horrible accident nearly a month earlier. Shinji makes attempts to understand Rei and her close relationship with his father.",
    "rating": "7.9"
  },
  "64ce6ae0-e79a-11e9-bb09-cd860116bbdb": {
    "season": "1",
    "number": "0",
    "date": "22 Jul. 2006",
    "title": "Unaired Premiere Episode",
    "description": "In New York, Peter Petrelli is the younger brother of Nathan Petrelli, an overly ambitious and unscrupulous candidate for the next New York congressman. Peter begins having strange dreams and begins to believe that he can fly, but Nathan is skeptic to his younger brother's claims. Peter decides to prove his theory and jumps from the roof of a building in an alley and his brother flies and saves him... revealing that Nathan has the ability to fly, not Peter. In Texas, cheerleader Claire Bennet learns that she is literally indestructible and can not harm herself or die....",
    "rating": "8.3"
  },
  "66444200-e79a-11e9-bb09-cd860116bbdb": {
    "season": "1",
    "number": "1",
    "date": "25 Sep. 2006",
    "title": "Chapter One 'Genesis'",
    "description": "In Manhattan, Peter Petrelli is the younger brother Nathan Petrelli an overly ambitious and unscrupulous candidate for the next New York congressman, and he dreams and believes that he can fly. He decides to prove his theory and jumps from the roof of a building in an alley and his brother flies and saves him. In Texas, cheerleader Claire Bennet learns that she is literally indestructible and can not harm herself or die. She saves a fireman in a fire in a train, but does not take the credit. In Tokyo, Hiro Nakamura believes he can control time and space continuum. In ...",
    "rating": "8.3"
  },
  "66444201-e79a-11e9-bb09-cd860116bbdb": {
    "season": "1",
    "number": "2",
    "date": "2 Oct. 2006",
    "title": "Chapter Two 'Don't Look Back'",
    "description": "When Nikki wakes up, she sees the two criminals dead in her garage. She brings her son and finds a brand new Cadillac in her name and the bodies in the trunk, with instructions and a map to bury the corpses in the desert. Peter awakes in the hospital and his mother tells him that his father was depressed and committed suicide. When Peter decides to jump from the terrace of his building, his brother Nathan discloses that both can fly. Hiro is teleported to the Times Square and finds a comic book written by Isaac Mendez telling his saga. He goes to Isaac studio, finds ...",
    "rating": "8.2"
  },
  "66444202-e79a-11e9-bb09-cd860116bbdb": {
    "season": "1",
    "number": "3",
    "date": "9 Oct. 2006",
    "title": "Chapter Three 'One Giant Leap'",
    "description": "As the \"Heroes\" continue to test their newfound extraordinary abilities, Claire tries to maintain a normal social life when a romance with the football quarterback takes a tragic turn. While Hiro convinces his friend that they are destined to travel to America to save the world, a frightened Niki follows instructions from a mysterious, unknown source that directs her to the middle of the desert. Meanwhile, Nathan uses Peter's accident to propel his political campaign. The elusive Sylar is being hunted by both Matt and the FBI, as well as Suresh, whose father's journal...",
    "rating": "8.2"
  },
  "66444203-e79a-11e9-bb09-cd860116bbdb": {
    "season": "1",
    "number": "4",
    "date": "16 Oct. 2006",
    "title": "Chapter Four 'Collision'",
    "description": "Suresh finally tracks down one of his father's fabled genetically advanced \"supermen.\" In Las Vegas, Hiro's plan backfires when he cautiously turns time to his advantage at the gambling tables. Niki's mafia debtors use their leverage to their benefit in a more elaborate scheme, while Nathan pays a personal visit to a wealthy Vegas contributor to raise additional campaign funds. Following a tragic turn at a bonfire, Claire's uncanny healing abilities are put to the ultimate test, but according to Isaac's paintings, her future could be fraught with even more peril. ...",
    "rating": "8.2"
  },
  "685d36f0-e79a-11e9-bb09-cd860116bbdb": {
    "season": "1",
    "number": "1",
    "date": "6 May 2019",
    "title": "1:23:45",
    "description": "Plant workers and firefighters put their lives on the line to control a catastrophic April 1986 explosion at a Soviet nuclear power plant.",
    "rating": "9.5"
  },
  "693b61f0-e79a-11e9-bb09-cd860116bbdb": {
    "season": "1",
    "number": "2",
    "date": "13 May 2019",
    "title": "Please Remain Calm",
    "description": "With untold millions at risk, Ulana makes a desperate attempt to reach Valery and warn him about the threat of a second explosion.",
    "rating": "9.7"
  },
  "693b61f1-e79a-11e9-bb09-cd860116bbdb": {
    "season": "1",
    "number": "3",
    "date": "20 May 2019",
    "title": "Open Wide, O Earth",
    "description": "Valery creates a detailed plan to decontaminate Chernobyl; Lyudmilla ignores warnings about her firefighter husband's contamination.",
    "rating": "9.6"
  },
  "693b61f2-e79a-11e9-bb09-cd860116bbdb": {
    "season": "1",
    "number": "4",
    "date": "27 May 2019",
    "title": "The Happiness of All Mankind",
    "description": "Valery and Boris attempt to find solutions to removing the radioactive debris; Ulana attempts to find out the cause of the explosion.",
    "rating": "9.5"
  },
  "693b61f3-e79a-11e9-bb09-cd860116bbdb": {
    "season": "1",
    "number": "5",
    "date": "3 Jun. 2019",
    "title": "Vichnaya Pamyat",
    "description": "Valery, Boris and Ulana risk their lives and reputations to expose the truth about Chernobyl.",
    "rating": "9.9"
  },
  "6ade1570-e79a-11e9-bb09-cd860116bbdb": {
    "season": "1",
    "number": "1",
    "date": "10 Sep. 1994",
    "title": "Gets Lost in Space",
    "description": "Topic: The Solar System. Arnold's cousin Janet joins the class on a trip to explore the solar system.",
    "rating": "8.2"
  },
  "6cb6cd10-e79a-11e9-bb09-cd860116bbdb": {
    "season": "1",
    "number": "2",
    "date": "17 Sep. 1994",
    "title": "For Lunch",
    "description": "Topic: Digestion. Arnold's so excited he doesn't have to go on a field trip! But when he accidentally swallows his miniaturized class, he becomes the field trip.",
    "rating": "8.2"
  },
  "6cb6cd11-e79a-11e9-bb09-cd860116bbdb": {
    "season": "1",
    "number": "3",
    "date": "24 Sep. 1994",
    "title": "Inside Ralphie",
    "description": "Topic: Germs. Ralphie is crushed when a fever keeps him home from school the day he's scheduled to host a FNN (Frizzle News Network) television broadcast on health. With Tyne Daly as Ralphie's mom.",
    "rating": "8.3"
  },
  "6cb6cd12-e79a-11e9-bb09-cd860116bbdb": {
    "season": "1",
    "number": "4",
    "date": "1 Oct. 1994",
    "title": "Gets Eaten",
    "description": "Topic: The Food Chain. Arnold and Keesha are in trouble when they forget to bring in their assignment on \"two things that go together.\"",
    "rating": "8.1"
  },
  "6cb6cd13-e79a-11e9-bb09-cd860116bbdb": {
    "season": "1",
    "number": "5",
    "date": "8 Oct. 1994",
    "title": "Hops Home",
    "description": "Topic: Habitats. When Wanda's pet frog, Bella, jumps out an open window, Ms. Frizzle shrinks the bus into a mechanical frog and takes her now tiny class on a hop-along adventure.",
    "rating": "7.7"
  },
  "6f104d70-e79a-11e9-bb09-cd860116bbdb": {
    "season": "1",
    "number": "1",
    "date": "2 Mar. 2009",
    "title": "I'm an Adult Now",
    "description": "Toby rescues a woman from a car wreck. Reading her mind, her child was abducted but she fears saying anything.",
    "rating": "7.1"
  },
  "70c06e70-e79a-11e9-bb09-cd860116bbdb": {
    "season": "1",
    "number": "2",
    "date": "4 Jun. 2009",
    "title": "Emotional Rescue",
    "description": "After saving a childhood friend from a burning building, Toby tracks town an arsonist that he believes might be responsible for a series of fires in the city.",
    "rating": "7.4"
  },
  "70c06e71-e79a-11e9-bb09-cd860116bbdb": {
    "season": "1",
    "number": "3",
    "date": "11 Jun. 2009",
    "title": "A Voice in the Dark",
    "description": "Toby encounters a crazed street person who may hold the key to locating a missing girl.",
    "rating": "7.7"
  },
  "70c06e72-e79a-11e9-bb09-cd860116bbdb": {
    "season": "1",
    "number": "4",
    "date": "18 Jun. 2009",
    "title": "Some Kinda Love",
    "description": "After meeting a young woman at a nightclub who is later found dead, Toby is considered the prime suspect and must clear his name.",
    "rating": "7.7"
  },
  "70c06e73-e79a-11e9-bb09-cd860116bbdb": {
    "season": "1",
    "number": "5",
    "date": "2 Jul. 2009",
    "title": "Lisa Says",
    "description": "When Toby saves a teenage boy from a gang beating, he learns that a series of drug store robberies may be linked to the runaway's turbulent past.",
    "rating": "7.6"
  },
  "72feecc0-e79a-11e9-bb09-cd860116bbdb": {
    "season": "1",
    "number": "1",
    "date": "23 Jun. 2011",
    "title": "Happiness",
    "description": "After a failed suicide attempt, Ryan notices that he sees the neighbor's dog as a person dressed dog costume.",
    "rating": "8.0"
  },
  "74515d60-e79a-11e9-bb09-cd860116bbdb": {
    "season": "1",
    "number": "2",
    "date": "30 Jun. 2011",
    "title": "Trust",
    "description": "Wilfred is angry after Ryan tricks him into going to the veterinarian.",
    "rating": "7.7"
  },
  "74515d61-e79a-11e9-bb09-cd860116bbdb": {
    "season": "1",
    "number": "3",
    "date": "7 Jul. 2011",
    "title": "Fear",
    "description": "Ryan discovers Wilfred left his wallet outside when they broke into Spencer's house.",
    "rating": "7.7"
  },
  "74515d62-e79a-11e9-bb09-cd860116bbdb": {
    "season": "1",
    "number": "4",
    "date": "14 Jul. 2011",
    "title": "Acceptance",
    "description": "Ryan feels obligated to repay his sister's help, however inappropriate, and therefore must shortly hand Wilfred into Darryl's daycare. The dog feels neglected and behaves strangely depressed.",
    "rating": "7.7"
  },
  "74515d63-e79a-11e9-bb09-cd860116bbdb": {
    "season": "1",
    "number": "5",
    "date": "21 Jul. 2011",
    "title": "Respect",
    "description": "Ryan and Wilfred volunteer at a hospice and discover Wilfred may have a remarkable secret talent.",
    "rating": "7.7"
  }
};

let s = {
  "tt4574334": {
    "type": "TV Series",
    "title": "Stranger Things",
    "year": "2016",
    "synopsis": "When a young boy disappears, his mother, a police chief, and his friends must confront terrifying supernatural forces in order to get him back.",
    "genres": [
      "Drama",
      "Fantasy",
      "Horror"
    ],
    "thumb_url": "https://m.media-amazon.com/images/M/MV5BZGExYjQzNTQtNGNhMi00YmY1LTlhY2MtMTRjODg3MjU4YTAyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SY132_CR0,0,89,132_AL_.jpg",
    "rating": "8.8",
    "directors": [
      "Matt Duffer",
      "Ross Duffer",
      "Shawn Levy",
      "Andrew Stanton",
      "Uta Briesewitz",
      "Rebecca Thomas"
    ],
    "actors": [
      "Winona Ryder",
      "David Harbour",      "Hunter Romanillos",
      "Patrick Seda",
      "James Stokes",
      "Todd Layne Thompson",
      "David Turner",
      "Savannah West"
    ],
    "episode": [
      "5dc08a30-e79a-11e9-bb09-cd860116bbdb",
      "5ec83630-e79a-11e9-bb09-cd860116bbdb",
      "5ec83631-e79a-11e9-bb09-cd860116bbdb",
      "5ec83632-e79a-11e9-bb09-cd860116bbdb",
      "5ec83633-e79a-11e9-bb09-cd860116bbdb"
    ]
  },
  "tt0112159": {
    "type": "TV Series",
    "title": "Neon Genesis Evangelion",
    "year": "1995",
    "synopsis": "A teenage boy finds himself recruited as a member of an elite team of pilots by his father.",
    "genres": [
      "Animation",
      "Action",
      "Drama"
    ],
    "thumb_url": "https://m.media-amazon.com/images/M/MV5BYjY1Y2ZmNDctZWQ3Yy00MTE3LTk2M2QtMjQ0MDA5ODVjMDEyXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SY132_CR0,0,89,132_AL_.jpg",
    "rating": "8.6",
    "directors": [
      "Hideaki Anno",
      "Kazuya Tsurumaki",
      "Hiroyuki Ishid척",
      "Tsuyoshi Kaga",
      "Keiichi Sugiyama",
      "Masayuki",
      "Seiji Mizushima",
      "Tetsuya Watanabe",
      "Ken And척",
      "Naoyasu Habu",
      "Sh척ichi Masuo",
      "Akira Takamura",
      "Minoru 횚hara",
      "Tensai Okamura",
      "Masahiko 횚tsuka"
    ],
    "actors": [
      "Spike Spencer",
      "Allison Keith",
      "Sue Ulu",
      "Amanda Winn Lee",
      "Tristan MacAvery",
      "Tiffany Grant",
      "Guil Lunde",
      "Matt Greenfield",
      "Kendra Benham",
      "Jason Lee",
      "Carrie Keranen",
      "Casey Mongillo",
      "Ryan Bartley",
      "Pedro de Aguill처n",
      "Erica Lindbeck",
      "Christine Marie Cabanos",
      "Daniel Mk Cohen",
      "Ray Chase",
      "JP Karliak",
      "Joe Pisano",
      "Kurt Stoll",
      "Stephanie McKeon",
      "Aaron Krohn",
      "Carol Amerson",
      "Ben Diskin",
      "Johnny Yong Bosch",
      "Billy Kametz",
      "Greg Chun",
      "Abby Trott",
      "Kotono Mitsuishi",
      "Yuriko Yamaguchi",
      "Megumi Ogata",
      "Robbie Friedman",
      "Henry Dittman",
      "Fumihiko Tachiki",
      "Hiro Y청ki",
      "Megumi Hayashibara",
      "Y청ko Miyamura",
      "Lucien Dodge",
      "Miki Nagasawa",
      "Cherami Leigh",
      "Takehito Koyasu",
      "Tetsuya Iwanaga",
      "Kim Sevier",
      "D.C. Douglas",
      "Tomokazu Seki",
      "K척ichi Nagano",
      "Monica Rial",
      "Genmu Kiyokawa",
      "K척ichi Yamadera",
      "Vic Mignogna",
      "Junko Iwao",
      "Laura Chapman",
      "Maria Kawamura",
      "Tomomichi Nishimura",
      "Mugihito",
      "Rick Peeples",
      "Motomu Kiyokawa",
      "Jin Yamanoi",
      "Hidenari Ugaki",
      "Edward Hong",
      "Clifford Chapin",
      "John Tyson",
      "Toshihiko Seki",
      "Michitaka Kobayashi",
      "H척ch청 횚tsuka",
      "Eiji Maruyama",
      "Hiroshi Naka",
      "Akira Ishida",
      "Akiko Hiramatsu",
      "Nagasumi Takashi",
      "Akiko Yajima",
      "Jessica Calvello",
      "Scott Kilgore",
      "Doug Medford",
      "Ben Nunez",
      "Layton Payne",
      "Lorraine Reyes",
      "Dan Rockwell",
      "Holly Vee",
      "Jos챕 Luis Casta챰eda",
      "Gene Kato",
      "Takashi Nagasako",
      "Katsumi Suzuki",
      "John Swasey",
      "Greg Ayres",
      "Ernesto Lezama",
      "Rebeca Pati챰o",
      "Rafael Rivera",
      "Kyle Sturdivant",
      "Liza Willert",
      "Charles C. Campbell",
      "Rob Mungle",
      "Yvonne Aquire",
      "Christine M. Auten",
      "Shelley Calene-Black",
      "Victor Carsrud",
      "Mandy Clark",
      "Melinda DeKay",
      "Jason Douglas",
      "Lauren Goodnight",
      "John Gremillion",
      "Mike Kleinhenz",
      "Kelly Manison",
      "George Manley",
      "Andy McAvin",
      "Chris Patton",
      "Melissa Cybele Sparks",
      "Randy Sparks"
    ],
    "episode": [
      "60b734f0-e79a-11e9-bb09-cd860116bbdb",
      "626d4960-e79a-11e9-bb09-cd860116bbdb",
      "626d4961-e79a-11e9-bb09-cd860116bbdb",
      "626d4962-e79a-11e9-bb09-cd860116bbdb",
      "626d4963-e79a-11e9-bb09-cd860116bbdb"
    ]
  },
  "tt0813715": {
    "type": "TV Series",
    "title": "Heroes",
    "year": "2006",
    "synopsis": "Common people discover that they have super powers. Their lives intertwine as a devastating event must be prevented.",
    "genres": [
      "Drama",
      "Fantasy",
      "Sci-Fi"
    ],
    "thumb_url": "https://m.media-amazon.com/images/M/MV5BMjI3ODU0OTQ1MV5BMl5BanBnXkFtZTgwNzI0MTQ2MzE@._V1_SX89_AL_.jpg",
    "rating": "7.5",
    "directors": [
      "Greg Beeman",
      "Allan Arkush",
      "Jeannot Szwarc",
      "Adam Kane",
      "Greg Yaitanes",
      "Paul A. Edwards",
      "Roxann Dawson",
      "Jim Chory",
      "John Badham",
      "Paul Shapiro",
      "David Semel",
      "Daniel Attias",
      "Sergio Mimica-Gezzan",
      "S.J. Clarkson",
      "Seith Mann",
      "Donna Deitch",
      "Ernest R. Dickerson",
      "Kevin Bray",
      "Lesli Linka Glatter",
      "Terrence O'Hara",
      "Holly Dale",
      "Anthony Hemingway",
      "David Von Ancken",
      "Ed Bianchi",
      "Kevin Dowling",
      "Tucker Gates",
      "Nathaniel Goodman",
      "Eric Laneuville",
      "Christopher Misiano",
      "Bryan Spicer",
      "David Straiton",
      "Michael Nankin",
      "Ron Underwood"
    ],
    "actors": [
      "Jack Coleman",
      "Hayden Panettiere",
      "Milo Ventimiglia",
      "Masi Oka",
      "Sendhil Ramamurthy",
      "Greg Grunberg",
      "James Kyson",
      "Adrian Pasdar",
      "Zachary Quinto",
      "Ali Larter",
      "Cristine Rose",
      "Ashley Crow",
      "Jimmy Jean-Louis",
      "Noah Gray-Cabey",
      "Randall Bentley",
      "Robert Knepper",
      "Santiago Cabrera",
      "Leonard Roberts",
      "Elizabeth Lackey",
      "Brea Grant",
      "Adair Tishler",
      "David Anders",
      "Dania Ramirez",
      "Dawn Olivieri",
      "Tawny Cypress",
      "David H. Lawrence XVII",
      "Kristen Bell",
      "Zeljko Ivanek",
      "Thomas Dekker",
      "George Takei",
      "Ntare Guma Mbaho Mwine",
      "Jessalyn Gilsig",
      "Stephen Tobolowsky",
      "Jamie Hector",
      "Blake Shields",
      "Madeline Zima",
      "Robert Forster",
      "Malcolm McDowell",
      "Deanne Bray",
      "Nicholas D'Agosto",
      "Nora Zehetner",
      "Ray Park",
      "Elisabeth R철hm",
      "Matthew John Armstrong",
      "Danielle Savre",
      "Clea DuVall",
      "Eric Roberts",
      "Shalim Ortiz",
      "Deirdre Quinn",
      "Alan Blumenfeld",
      "Dana Davis",
      "Todd Stashwick",
      "Missy Peregrym",
      "Eriko Tamura",
      "Katie Carr",
      "Sally Champlin",
      "Justin Evans",
      "Daryl Crittenden",
      "Jackson Wurth",
      "Richard Roundtree",
      "Quin Baron",
      "Reed Baron",
      "Jayma Mays",
      "Joshua Rush",
      "Sasha Pieterse",
      "Saemi Nakamura",
      "Matt Lanter",
      "Harry Perry",
      "Rena Sofer",
      "Nichelle Nichols",
      "Christopher Eccleston",
      "Jonny Siew",
      "Dianna Agron",
      "Barry Shabaka Henley",
      "Assaf Cohen",
      "Holt McCallany",
      "Shishir Kurup",
      "Eugene Byrd",
      "Taylor Cole",
      "Stacy Haiduk",
      "Ron Perkins",
      "Colby French",
      "Sekai Murashige",
      "Dominic Keating",
      "Adetokumboh M'Cormack",
      "Josh Clark",
      "Erick Avari",
      "Reginald James",
      "Francis Capra",
      "Janel Parrish",
      "Julian de la Celle",
      "Tessa Thompson",
      "Ellen Greene",
      "Dan Byrd",
      "Rick Worthy",
      "Carlease Burke",
      "Bruce Boxleitner",
      "Kevin Chamberlin",
      "Kat Purgal",
      "Erin Allin O'Reilly",
      "Kaleigh Ryan",
      "Demetrius Grosse",
      "Brian Tarantina",
      "Franc Ross",
      "Carlon Jeffery",
      "Mark Vanselow",
      "David Ury",
      "Mark Colson",
      "Milos Milicevic",
      "Tohoru Masamune",
      "Tamlyn Tomita",
      "Ronald Guttman",
      "Adam Jamal Craig",
      "Ken Lally",
      "Link Baker",
      "Doug Haley",
      "Darryl Chan",
      "Louise Fletcher",
      "Daniel Newman",
      "Mark L. Young",
      "Kate Vernon",
      "Justin Baldoni",
      "Ravi Kapoor",
      "Ernie Hudson",
      "Dawn-Lyen Gardner",
      "Gabriel Olds",
      "Stana Katic",
      "Andrew Connolly",
      "Kavi Ladnier",
      "Cary-Hiroyuki Tagawa",
      "Rachel Melvin",
      "Karri Turner",
      "Bill Fagerbakke",
      "Michael Dorn",
      "Paula Newsome",
      "Sakina Jaffrey",
      "Ray Baker",
      "Japheth Gordon",
      "Swoosie Kurtz",
      "Joel West",
      "Adam Lazarre-White",
      "Jeanette Brox",
      "Bernadette Speakes",
      "Danica Stewart",
      "John Prosky",
      "Chad Faust",
      "Candice Patton",
      "Garrett Masuda",
      "Jason E. Kelley",
      "Nicole Bilderback",
      "Rick Peters",
      "Missi Pyle",
      "Jeff Campbell",
      "Mark Allan Stewart",
      "Cory Hardrict",
      "T.W. Leshner",
      "Seth Green",
      "Breckin Meyer",
      "Andre Royo",
      "Jack Wallace",
      "Dutch Johnson",
      "Glenn Hetrick",
      "Jordan Dang",
      "Roberto 'Sanz' Sanchez",
      "Michael Maury",
      "Geno Monteiro",
      "Satomi Okuno",
      "Rene Cadet",
      "Max Amini",
      "Ashlee Gillespie",
      "Mio Takada",
      "Matthew Wiese",
      "Karl T. Wright",
      "Jean-Pierre Vertus",
      "Ben Murray",
      "Claudia DiFolco",
      "Mark Nearing",
      "Kurando Mitsutake",
      "Joe Bucaro III",
      "Javin Reid",
      "Kenji Nakamura",
      "Timon Kyle Durrett",
      "Greg Wrangler",
      "Sara Solomon Johnson",
      "Russell B. McKenzie",
      "Ryan Smith",
      "Joanna Cassidy",
      "Bonnie Bentley",
      "Cazimir Milostan",
      "Keisuke Hoashi",
      "Elizabeth Ann Bennett",
      "Olga Sosnovska",
      "Elizabeth Roberts",
      "John F. Schaffer",
      "Madden Page",
      "Tehmina Sunny",
      "Kevin Alejandro",
      "Jake McLaughlin",
      "Raphael Sbarge",
      "Kellan Lutz",
      "Ramona DuBarry",
      "Christine Adams",
      "Dan Desmond",
      "Diana Scarwid",
      "Graham Beckel",
      "Sheku Fofana",
      "Katherine Boecher",
      "Moira Kelly",
      "Manuel Urrego",
      "Sherri Saum",
      "Bonnie Burroughs",
      "Kenneth Choi",
      "William Duffy",
      "Akihiro Kitamura",
      "Alexa Nikolas",
      "Michael B. Silver",
      "Nayo Wallace",
      "Stephen Monroe Taylor",
      "Tina Lifford",
      "Sterling Beaumon",
      "Kevin Christy",
      "Edwin Hodge",
      "Bryce Hurless",
      "Rolando Molina",
      "David Pompeii",
      "Ned Schmidtke",
      "Ned Vaughn",
      "Antonio Fargas",
      "Keith Burke",
      "Amrapali Ambegaokar",
      "Jayson Blair",
      "Nigel Gibbs",
      "Edward Gusts",
      "Clint Howard",
      "Edwin Kho",
      "Laura Marano",
      "Frank Pacheco",
      "Candace Smith",
      "Hank Stratton",
      "Eidan Hanzei",
      "Jacqueline Pinol",
      "Richard Steinmetz",
      "Mark Christopher Lawrence",
      "Rebecca Tilney",
      "Susan Angelo",
      "Heather Ankeny",
      "Sofie Calderon",
      "Julia Campbell",
      "Kimberly Estrada",
      "Zack Lively",
      "Michael D. Nye",
      "Jamie Tisdale",
      "Jessica Whitaker",
      "K Callan",
      "Kenneth Colom",
      "Cary Y. Mizobe",
      "Ai Yoshihara",
      "Archie Kao",
      "Dean Napolitano",
      "Elya Baskin",
      "Ivonne Coll",
      "Rachel Kimsey",
      "Stephen Foz McDermott",
      "Brian Morri",
      "Rusty Schwimmer",
      "Juno Ishida",
      "William Katt",
      "Michael Croner",
      "Lauren Hudson",
      "Daniel Kash",
      "Aleene Khoury",
      "Mara LaFontaine",
      "Omar Leyva",
      "Natalie Salins",
      "Garrett Strommen",
      "Sydney Sweeney",
      "Cloie Wyatt Taylor",
      "Steve Tom",
      "Sean Carrigan",
      "Meghan McCaig",
      "Paul Raci",
      "Christine Avila",
      "Ethan Cohn",
      "Lyndsy Fonseca",
      "Shang Forbes",
      "Tami-Adrian George",
      "Bart McCarthy",
      "Jaime Ray Newman",
      "Meera Simhan",
      "Sean Yonamine",
      "Michael Carven",
      "Yawar Charlie",
      "Danielle Crumble",
      "Benjamin Fitch",
      "Randy Flagler",
      "Casey Kringlen",
      "Angela Martinez",
      "Douglas Tait",
      "Nick Ubaldi",
      "Marie Wong",
      "Justin Dray",
      "John Gerbin",
      "Conroe Brooks",
      "Stephen Full",
      "Brad Greenquist",
      "Christina Haag",
      "Eijiro Ozaki",
      "Brian Palermo",
      "Jeff Staron",
      "David Atkinson",
      "Josh Barker",
      "William Charlton",
      "Anna Clark",
      "Deanna Lee Douglas",
      "Eddie Driscoll",
      "John Glover",
      "Jonathan Goldstein",
      "Meeghan Holaway",
      "Darren Kendrick",
      "Bryan Krasner",
      "Pramode Kumar",
      "Dan Shadwell",
      "Dusty Sorg",
      "Don Tiffany",
      "Carrie Wiita",
      "Gregory Hoyt",
      "Kelli Kirkland",
      "Matt Sigloch",
      "Michael Reilly Burke",
      "Stephen Spinella",
      "Ian Gomez",
      "Mark Harelik",
      "Tak Kubota",
      "John Lacy",
      "Stan Lee",
      "Kiernan Shipka",
      "Lauren Stamile",
      "Edward Carnevale",
      "Sonalii Castillo",
      "Kiko Ellsworth",
      "China Anderson",
      "Sam Cohen",
      "Jason Graham",
      "Shauntay Hinton",
      "Zachary Knower",
      "Aarti Mann",
      "Wes Ramsey",
      "Steve Seagren",
      "Carlson Young",
      "Heather Cooney",
      "Shevaun Kastl",
      "Christopher May",
      "Clay Wilcox",
      "Alex Fernandez",
      "Jason Foster",
      "David S. Jung",
      "Brian Kimmet",
      "Paul Perri",
      "Rikio",
      "Sage Kirkpatrick",
      "John Lee Ames",
      "Allison Paige",
      "Ramesh Pandey",
      "Cory Tucker",
      "Greg Zola",
      "Allyson Roche",
      "Mary Wickliffe",
      "Toni Lewis",
      "Hector Luis Bustamante",
      "Jesse Corti",
      "Paul Ganus",
      "Bobby Hosea",
      "Noriaki Ito",
      "Matt North",
      "Sabrina Perez",
      "Jeremy Gram Weaver",
      "Doralicia",
      "Matt Biedel",
      "Helen Eigenberg",
      "Jennie Fahn",
      "David Berman",
      "Matt Bushell",
      "Michael Milhoan",
      "Yareli Arizmendi",
      "David Barrera",
      "John Ross Bowie",
      "Gerardo Celasco",
      "Benjamin Byron Davis",
      "Kenjun Kawawata",
      "Lilas Lane",
      "Monica Louwerens",
      "Thomas Robinson",
      "Matt Shallenberger",
      "Ryan Todd",
      "Cindy Chiu",
      "Mercedes Colon",
      "Frank Maharajh",
      "Robert Mammana",
      "Jim Petersmith",
      "Gina St. John",
      "Charly Emery",
      "Kristin Dos Santos",
      "Adam Harrington",
      "Peyton Hinson",
      "Tadao Tomomatsu",
      "Emerson Brooks",
      "Markus Flanagan",
      "Loren Lester",
      "John Antonini",
      "Zoe Bolden",
      "Roger Bridges",
      "Kelly Michaels",
      "Shane Conrad",
      "Dennis Chavis",
      "Kate Connor",
      "Mike Foy",
      "Riki Lindhome",
      "Jonathan T. Floyd",
      "Rachelle Jacoby",
      "Jose Rosario",
      "Dominic Paolo Testa",
      "B.J. Clinkscales",
      "J. David Shanks",
      "Brian Skala",
      "Felipe Alejandro",
      "Everett Kelsey",
      "Omid Abtahi",
      "Danielle Morrow",
      "Chris Hendrie",
      "Ilene Perez",
      "Countrified Wedman",
      "Erik Betts",
      "Dustin Hess",
      "Cole Williams",
      "Dean Cudworth",
      "Jarvis W. George",
      "Mark Anthony Cage",
      "Ian Quinn",
      "Rick Scarry",
      "Brent Tarnol",
      "Jessica Anne Bogart",
      "Jermaine Jackson",
      "Irina Maleeva",
      "Nina Mann",
      "Annie McKnight",
      "Taira Soo",
      "James Storm",
      "James Storm",
      "Jim Storm",
      "Grifon Aldren",
      "Scott Lowell",
      "James McAndrew",
      "Franco Vega",
      "Carl Ciarfalio",
      "Eliza Coleman",
      "Matt Eyde",
      "Ossie Mair",
      "Robert Rigamonti",
      "Angela Chee",
      "Nicole Clifford",
      "Liisa Cohen",
      "Martez Covington",
      "Lateef Crowder",
      "Patrick Faucette",
      "Laivan Greene",
      "Roberto Medina",
      "Chris Oliver",
      "Kimleigh Smith",
      "James D. Dever",
      "Lauren Leah Mitchell",
      "Ameenah Kaplan",
      "Mikey Kawata",
      "Wally Rudolph",
      "Paydin LoPachin",
      "Natalie Amenula",
      "Steve Gibbons",
      "Christopher Guyton",
      "Jack Guzman",
      "Louis Iacoviello",
      "Tatiyana Cotton",
      "Lazarus Jackson",
      "Christopher Mann",
      "Michael Cutt",
      "Yuki Matsuzaki",
      "Kelvin Brown",
      "Beau Dremann",
      "Kevin P. Kearns",
      "Kiko Kiko",
      "D. Elliot Woods",
      "Logan Alexander",
      "Travis Guba",
      "Jason Konopisos-Alvarez",
      "James Devoti",
      "Tiffany Hines",
      "Benjamin J. Cain Jr.",
      "Dan Warner",
      "Toshiya Agata",
      "Leslie Thurston",
      "Marine Fujisawa",
      "Rene L. Moreno",
      "Darren Keefe Reiher",
      "Stephen W. Schriver",
      "Marisa Tayui",
      "Shane Woodson",
      "Julie Pop",
      "Pamela Shaddock",
      "Jarret Wright",
      "Julie Costello",
      "Ewan Chung",
      "Blair Hickey",
      "Alan Evrard",
      "Shawnie Costello",
      "Casey Washington",
      "Cindy Gilbert",
      "Garrick Dixon",
      "Jacob Hashem",
      "Corey Allen Kotler",
      "Wiley M. Pickett",
      "Rob Swanson",
      "John Thaddeus",
      "Americus Abesamis",
      "Robb Conner",
      "Julio Leal",
      "Jason Giffin",
      "Mohammad Kavianpour",
      "Michael Laren",
      "Marilyn Monrovia",
      "Kie Spring",
      "Eric Shackelford",
      "Max Decker",
      "Alan Mueting",
      "Rick L. Dean",
      "Hunter James Mckeever",
      "Kate Scott",
      "Emily Adams",
      "Stewart Tain",
      "Ayla Rose Barreau",
      "Leslie Berger",
      "Courtney Claghorn",
      "Nicky Endres",
      "Andrea Fellers",
      "Liz Forde",
      "Monte Hunter",
      "Helen Kelly",
      "Maurice LaMarche",
      "Prateek Saxena",
      "Tiffany Tynes",
      "David Black",
      "Joshua James",
      "Padraic Keohane",
      "Karri Krause",
      "Justin Loyal",
      "Ed Moy",
      "Nathan Mussell",
      "Rey Mysterio",
      "James Castle Stevens",
      "Tj Austin",
      "Chris Cleveland",
      "Tom Corn",
      "Kanin Howell",
      "Nancy McCrumb",
      "Kim Meredith",
      "Joseph J. Micucci",
      "Jared Farid Ward",
      "Kazumi Aihara",
      "Joseph Bayard",
      "Billy Joe Brewer III",
      "Cam Clarke",
      "Jon Donahue",
      "Daniel S. Ehrlich",
      "Steve Filice",
      "Rafael Francisco",
      "Gregory George Frank",
      "Bruce Frausto",
      "Brandy Futch",
      "Itamar Gelbman",
      "Wade Harlan",
      "Brian Harvey",
      "Jesse Heiman",
      "Lynne Jacobellis",
      "Lakrishi Kindred",
      "Arune Kital",
      "Lauren L. Lawson",
      "Natalina Maggio",
      "Joshua McCabe",
      "Markeia McCarty",
      "Candace Miller",
      "Jennifer Lynn O'Hara",
      "Sarita Ospina",
      "Beverly Overstreet",
      "Laura Owen",
      "Lance Patrick",
      "Ginger Pauley",
      "James Peyton",
      "Audrey Povar",
      "Garrett Ryan",
      "Gregory Schmauss",
      "Ciarra Siller",
      "Stephanie Silver",
      "Sienna Sky",
      "Michael A. Templeton",
      "Stephan Todd",
      "Kelley Welte",
      "Matt Barriga",
      "Megan George",
      "Giovanni V. Giusti",
      "Jade Olsen",
      "Gracie Rae",
      "Robert Rueda",
      "Frank Scozzari",
      "Chester A. Sims II",
      "Utvick Melanie",
      "Denise Vasquez",
      "George F. Watson",
      "Maria Zambrana"
    ],
    "episode": [
      "64ce6ae0-e79a-11e9-bb09-cd860116bbdb",
      "66444200-e79a-11e9-bb09-cd860116bbdb",
      "66444201-e79a-11e9-bb09-cd860116bbdb",
      "66444202-e79a-11e9-bb09-cd860116bbdb",
      "66444203-e79a-11e9-bb09-cd860116bbdb"
    ]
  },
  "tt7366338": {
    "type": "TV Series",
    "title": "Chernobyl",
    "year": "2019",
    "synopsis": "In April 1986, an explosion at the Chernobyl nuclear power plant in the Union of Soviet Socialist Republics becomes one of the world's worst man-made catastrophes.",
    "genres": [
      "Drama",
      "History",
      "Thriller"
    ],
    "thumb_url": "https://m.media-amazon.com/images/M/MV5BNTEyYmIzMDUtNWMwNC00Y2Q1LWIyZTgtMGY1YzUxOTAwYTAwXkEyXkFqcGdeQXVyMjIyMTc0ODQ@._V1_SY132_CR0,0,89,132_AL_.jpg",
    "rating": "9.5",
    "directors": [
      "Johan Renck"
    ],
    "actors": [
      "Jessie Buckley",
      "Jared Harris",
      "Stellan Skarsg책rd",
      "Adam Nagaitis",
      "Emily Watson",
      "Paul Ritter",
      "Robert Emms",
      "Sam Troughton",
      "Karl Davies",
      "Michael Socha",
      "Laura Elphinstone",
      "Jan Ricica",
      "Alan Williams",
      "Adrian Rawlins",
      "Con O'Neill",
      "Douggie McMeekin",
      "Nadia Clifford",
      "David Dencik",
      "Gerard Kearns",
      "Adam Lundgren",
      "Mark Lewis Jones",
      "Michael Shaeffer",
      "Jay Simpson",
      "Jamie Sives",
      "Ron Cook",
      "Povilas Jatkevicius",
      "Joshua Leese",
      "Ross Armstrong",
      "Paulius Markevicius",
      "Billy Postlethwaite",
      "Ralph Ineson",
      "Baltasar Breki Samper",
      "Barry Keoghan",
      "Philip Barantini",
      "Karolis Kasperavicius",
      "Amanda Drew",
      "Oscar Dyekj챈r Giese",
      "Cait Davis",
      "Darius Petkevicius",
      "Donald Sumpter",
      "Tomas Zaibus",
      "June Watson",
      "Josef Altin",
      "Matthew Needham",
      "Sergejus Ivanovas",
      "Rosie Sheehy",
      "Caoilfhionn Dunne",
      "Pandora Colin",
      "Alexej Manvelov",
      "Fares Fares",
      "Josef Davies",
      "Simonas Dovidauskas",
      "Rachel Atkins",
      "Velta Zygure",
      "Paulius Cizinauskas",
      "Mark Bagnall",
      "Michael McElhatton",
      "Hilton McRae",
      "Ian Pirie",
      "Sam Strike",
      "Alex Ferns",
      "Kieran O'Brien",
      "Andrew Sheridan",
      "James Cosmo",
      "Sammy Hayman",
      "Lukas Malinauskas",
      "Arnas Danusas",
      "Marius Karolis Gotbergas",
      "Peter Guinness",
      "Michael Colgan",
      "Laurence Spellman",
      "James Kermack",
      "Alison Pargeter",
      "Victor McGuire",
      "Karolis Vilkas",
      "Sakalas Uzdavinys",
      "Sarunas Datenis",
      "Deividas Breive",
      "Matas Dirgincius",
      "Aidas Jurgaitis",
      "Aiste Gramantaite",
      "Caolan Byrne",
      "Stephen Bisland",
      "Alex Blake",
      "Daniel Crossley",
      "Lucy Russell",
      "Diarmaid Murtagh",
      "Natasha Radski",
      "Yitzchak Averbuch",
      "Joe Tucker",
      "Bartas Erminas",
      "Roman Listopad",
      "Danguole Ragazinskaite"
    ],
    "episode": [
      "685d36f0-e79a-11e9-bb09-cd860116bbdb",
      "693b61f0-e79a-11e9-bb09-cd860116bbdb",
      "693b61f1-e79a-11e9-bb09-cd860116bbdb",
      "693b61f2-e79a-11e9-bb09-cd860116bbdb",
      "693b61f3-e79a-11e9-bb09-cd860116bbdb"
    ]
  },
  "tt0108847": {
    "type": "TV Series",
    "title": "The Magic School Bus",
    "year": "1994",
    "synopsis": "An eccentric school-teacher takes her class on wondrous educational field trips with the help of a magical school bus.",
    "genres": [
      "Animation",
      "Adventure",
      "Comedy"
    ],
    "thumb_url": "https://m.media-amazon.com/images/M/MV5BNzI3YTI5NzQtNWIwOC00NTM3LWJjODEtYzE0YjcyZTc3ODg1XkEyXkFqcGdeQXVyNDgyODgxNjE@._V1_SY132_CR2,0,89,132_AL_.jpg",
    "rating": "7.9",
    "directors": [
      "Larry Jacobs",
      "Charles E. Bastien"
    ],
    "actors": [
      "Lily Tomlin",
      "Daniel DeSanto",
      "Erica Luttrell",
      "Tara Meyer",
      "Maia Filar",
      "Lisa Jai",
      "Stuart Stone",
      "Malcolm-Jamal Warner",
      "Danny Tamberelli",
      "Andre Ottley-Lorant",
      "Amos Crawley",
      "Max Beckford",
      "Susan Blu",
      "Renessa Blitz",
      "Don Dickinson",
      "Ashley Taylor",
      "Ashley Brown",
      "Kevin Zegers",
      "Gil Filar",
      "Paul Winfield",
      "Ruby Smith-Merovitz",
      "Byron Abalos",
      "Chantellese Kent",
      "Asia Vieira",
      "Lance Paton",
      "Melissa Bathory",
      "Shannon Duff",
      "Dov Tiefenbach",
      "Tyne Daly",
      "Jacelyn Holmes",
      "James Rankin",
      "Rosalind Chao",
      "Annick Obonsawin",
      "Kate Rodriguez",
      "Nick Bujnak",
      "Blake McGrath",
      "Noah Reid",
      "Tyrone Savage",
      "Ed Begley Jr.",
      "Robby Benson",
      "Carol Channing",
      "Dom DeLuise",
      "Tony Randall",
      "Cindy Williams",
      "Dan Marino",
      "Swoosie Kurtz",
      "Edward Asner",
      "Matt Frewer",
      "Dolly Parton",
      "Alex Trebek",
      "Jessica Walter",
      "Dana Elcar",
      "Elliott Gould",
      "Dominic Zamprogna",
      "Elizabeth Hanna",
      "Eartha Kitt",
      "Benjamin Plener",
      "Jonathan Schwartz",
      "Robin Weekes",
      "Katie Coristine",
      "Edward James Olmos",
      "Stacey Wheal",
      "Karen Bernstein",
      "Natasha Greenblatt",
      "John White",
      "Gene Mack",
      "Daniel Stemer",
      "Jane Luk",
      "Neil Crone",
      "Michael Barry",
      "Alissa Berg",
      "Jamie Leigh Rainey",
      "George Buza",
      "Michael Caloz",
      "Sherman Hemsley",
      "Gary Krawford",
      "Rita Moreno",
      "Sarena Paton",
      "Michael York",
      "Christopher Bell",
      "Fiona Hart",
      "Paul Bernstein",
      "Robert Bockstael",
      "Benedict Campbell",
      "Dabney Coleman",
      "Tom Cruise",
      "Jeff Davis",
      "Kerry Duff",
      "Nicky Guadagni",
      "Tabby Johnson",
      "Cody Jones",
      "Wynonna Judd",
      "Malcolm McDowell",
      "Bebe Neuwirth",
      "Leah Renee",
      "Ron Rubin",
      "Sam Seder",
      "Richard Yearwood"
    ],
    "episode": [
      "6ade1570-e79a-11e9-bb09-cd860116bbdb",
      "6cb6cd10-e79a-11e9-bb09-cd860116bbdb",
      "6cb6cd11-e79a-11e9-bb09-cd860116bbdb",
      "6cb6cd12-e79a-11e9-bb09-cd860116bbdb",
      "6cb6cd13-e79a-11e9-bb09-cd860116bbdb"
    ]
  },
  "tt1181541": {
    "type": "TV Series",
    "title": "The Listener",
    "year": "2009",
    "synopsis": "A young paramedic discovers he has telepathic powers.",
    "genres": [
      "Crime",
      "Drama",
      "Fantasy"
    ],
    "thumb_url": "https://m.media-amazon.com/images/M/MV5BMTg5MDk4Mzk1OV5BMl5BanBnXkFtZTcwNjYxMTAyOA@@._V1_SY132_CR1,0,89,132_AL_.jpg",
    "rating": "6.7",
    "directors": [
      "Clement Virgo",
      "Kari Skogland",
      "Peter Stebbings",
      "Bradley Walsh",
      "Farhad Mann",
      "Charles Binam챕",
      "Robert Lieberman",
      "Paul Fox",
      "Stephen Surjik",
      "Cal Coons",
      "Stefan Pleszczynski",
      "Harvey Crossland",
      "Don McCutcheon",
      "T.W. Peacocke",
      "Ken Girotti",
      "T.J. Scott",
      "John L'Ecuyer",
      "Keith Samples",
      "James Dunnison"
    ],
    "actors": [
      "Craig Olejnik",
      "Ennis Esmer",
      "Lauren Lee Smith",
      "Rainbow Francks",
      "Peter Stebbings",
      "Myl챔ne Dinh-Robic",
      "Tara Spencer-Nairn",
      "Arnold Pinnock",
      "Melanie Scrofano",
      "Anthony Lemke",
      "Kris Holden-Ried",
      "Lisa Marcos",
      "Natalie Krill",
      "Lara Jean Chorostecki",
      "John Fleming",
      "Colm Feore",
      "Greg Ellwand",
      "Ingrid Kavelaars",
      "Rachel Skarsten",
      "Jee-Yun Lee",
      "Gordon Pinsent",
      "Stephen McHattie",
      "Paulino Nunes",
      "Peter Outerbridge",
      "Kristopher Turner",
      "Pedro Salv챠n",
      "Kristina Pesic",
      "Jesse Bostick",
      "Tenika Davis",
      "Matthew Bennett",
      "Xhemi Agaj",
      "Phillip Jarrett",
      "Helen Johns",
      "Bernadette Couture",
      "Janet Porter",
      "James Cade",
      "David Collins",
      "Joe Bostick",
      "Jade Salsman",
      "A.C. Peterson",
      "Naomi Snieckus",
      "Don Francks",
      "Mark Rendall",
      "Michelle Nolden",
      "Michelle Adams",
      "Mayko Nguyen",
      "Sebastian Pigott",
      "Dean Armstrong",
      "Aaron Ashmore",
      "Cl챕 Bennett",
      "Cynthia Dale",
      "Ryan Robbins",
      "John Ralston",
      "Nola Augustson",
      "Stephen Bogaert",
      "Kristin Booth",
      "Greg Bryk",
      "Brendan Fletcher",
      "Patrick Galligan",
      "Keir Gilchrist",
      "Diego Klattenhoff",
      "Steph Song",
      "Devon Bostick",
      "Kevin Jubinville",
      "Maurice Dean Wint",
      "Fefe Dobson",
      "Chad Faust",
      "Jonny Harris",
      "Shawn Roberts",
      "Ian Tracey",
      "Kenneth Welsh",
      "Holly Deveaux",
      "Stefano DiMatteo",
      "Athena Karkanis",
      "Rayisa Kondracki",
      "Damon Runyan",
      "Cindy Sampson",
      "Steve Belford",
      "Matt Gordon",
      "Kristen Hager",
      "Kevin Hanchard",
      "Hayley Lochner",
      "Sean Lu",
      "Tatiana Maslany",
      "Sherry Miller",
      "Merwin Mondesir",
      "Tara Rosling",
      "Tim Rozon",
      "Charlotte Sullivan",
      "Yannick Bisson",
      "Dmitry Chepovetsky",
      "Matt Cooke",
      "Thomas Craig",
      "Rachael Crawford",
      "Stuart Hughes",
      "Mimi Kuzyk",
      "James Purcell",
      "James Allodi",
      "Katie Boland",
      "K.C. Collins",
      "Daniel Fathers",
      "Sandrine Holt",
      "Thomas Mitchell",
      "Glen Suitor",
      "Rossif Sutherland",
      "Wes Williams",
      "Lisa Berry",
      "Jefferson Brown",
      "Justin Chatwin",
      "Michael Cram",
      "Richard de Klerk",
      "Gina Holden",
      "Elias Theodorou",
      "Loretta Yu",
      "Natalie Brown",
      "Scott Gibson",
      "Riley Gilchrist",
      "Gabriel Hogan",
      "Neil Napier",
      "Drew Nelson",
      "Robin Wilcock",
      "Brittany Allen",
      "Warren Chow",
      "Angela Fusco",
      "Daniel Kash",
      "Shauna MacDonald",
      "Lee Rumohr",
      "Dan Warry-Smith",
      "Adam Kenneth Wilson",
      "Steve Bacic",
      "Joanne Boland",
      "Sabrina Grdevich",
      "Jonathan Higgins",
      "Steven McCarthy",
      "Romano Orzari",
      "Kristen Thomson",
      "Christopher Bolton",
      "Adam Butcher",
      "Larry Day",
      "Sergio Di Zio",
      "Ellen Dubin",
      "Jeff Geddis",
      "Karen Holness",
      "Stephan James",
      "Judah Katz",
      "Matthew D. Matteo",
      "Anand Rajaram",
      "Raoul Bhaneja",
      "Noah Dalton Danby",
      "Joanna Douglas",
      "Michael Filipowich",
      "Erin Karpluk",
      "Pat Mastroianni",
      "Jane McGregor",
      "Andrew Moodie",
      "Gord Rand",
      "Rick Roberts",
      "Jewel Staite",
      "George Tchortov",
      "Alan Van Sprang",
      "John Bourgeois",
      "Tricia Braun",
      "Shawn Doyle",
      "David Patrick Flemming",
      "Noam Jenkins",
      "Laura Miyata",
      "Grant Nickalls",
      "Tommie-Amber Pirie",
      "Julian Richings",
      "Tygh Runyan",
      "Jeannette Sousa",
      "Dewshane Williams",
      "Dakota Goyo",
      "Kean Lui",
      "Barbara Mamabolo",
      "Gerry Mendicino",
      "Michael Miller",
      "Leanne Poirier Greenfield",
      "Sarah Power",
      "Liisa Repo-Martell",
      "Booth Savage",
      "Mark Whelan",
      "Pragna Desai",
      "Phyllis Ellis",
      "Alexz Johnson",
      "William MacDonald",
      "Michael Majeski",
      "Alex Paxton-Beesley",
      "Al Sapienza",
      "Matt Baram",
      "Krista Bridges",
      "Fulvio Cecere",
      "Eugene Clark",
      "Tony Craig",
      "Carolyn Goff",
      "Eugene Lipinski",
      "Robert Mauriell",
      "Debra McCabe",
      "Corey Sevier",
      "Linda Thorson",
      "Terra Vnesa",
      "Marc Bendavid",
      "Inga Cadranel",
      "Romina D'Ugo",
      "Mark Gibson",
      "Adrian G. Griffiths",
      "Tyler Hynes",
      "Pascal Langdale",
      "Michael Mando",
      "Gabrielle Miller",
      "Kimberly-Sue Murray",
      "Krystin Pellerin",
      "Damir Andrei",
      "Kristi Angus",
      "Ryan Blakely",
      "Ari Cohen",
      "Jon Cor",
      "Craig Eldridge",
      "Wesley French",
      "Lara Gilchrist",
      "Bruce Gray",
      "Sandy Jobin-Bevans",
      "Jordan Johnson-Hinds",
      "Shawn Lawrence",
      "Emily Piggford",
      "Damien Atkins",
      "Todd Campbell",
      "John Evans",
      "Darrel Gamotin",
      "Kjartan Hewitt",
      "Olivia Jones",
      "Janet Land",
      "Barbara Radecki",
      "Joel Rinzler",
      "Danny Waugh",
      "Stewart Arnott",
      "Frank Chiesurin",
      "Jonathan Duhamel",
      "Thomas Hauff",
      "Allie MacDonald",
      "Doug MacLeod",
      "Jasmine Richards",
      "Sebastien Roberts",
      "Michael Therriault",
      "Elias Toufexis",
      "Lawrence Bayne",
      "Shaun Benson",
      "Conrad Coates",
      "Peter DaCunha",
      "Laura de Carteret",
      "Martin Donovan",
      "James Gilbert",
      "Luke Gordon",
      "Barclay Hope",
      "Sean McCann",
      "Zoie Palmer",
      "Erin Pitt",
      "Chuck Shamata",
      "Benz Antoine",
      "Angela Asher",
      "Nick Bateman",
      "Evan Buliung",
      "Megan Fahlenbock",
      "Kristin Fairlie",
      "Ray Galletti",
      "Andrea Grant",
      "Christopher Jacot",
      "Joel Keller",
      "Mishael Morgan",
      "Aaron Poole",
      "Darrin Baker",
      "Katherine Barrell",
      "Anthony Grant",
      "Allison Hossack",
      "Brock Johnson",
      "Theresa Joy",
      "Thomas Michael",
      "Laura Nordin",
      "Dylan Taylor",
      "Marie Ward",
      "Wayne Ward",
      "Kimmy Choi",
      "Jim Codrington",
      "Richlin Fharlo",
      "Murray Furrow",
      "Carlos Gonzalez-Vio",
      "Judy Marshak",
      "Louise Nicol",
      "Kim Schraner",
      "Jimi Shlag",
      "Kate Spurgeon",
      "Tyler Stevenson",
      "Nick Baillie",
      "Ron Basch",
      "J. Adam Brown",
      "Rod Campbell",
      "Jonas Chernick",
      "Richard Fagon",
      "Janet Lo",
      "Ruth Marshall",
      "Joseph Pierre",
      "Rekha Sharma",
      "Ryan Turner",
      "Vlada Verevko",
      "Troy Blundell",
      "Ian Busher",
      "Tim Fellingham",
      "Richard Harte",
      "Dion Johnstone",
      "Robin Kasyanov",
      "Andrew Kraulis",
      "Kristin Lehman",
      "Yanna McIntosh",
      "Rafal Mickiewicz",
      "Geoffrey Pounsett",
      "Richard Zeppieri",
      "Allen Altman",
      "Demore Barnes",
      "Will Bowes",
      "Steve Boyle",
      "Tim Doiron",
      "David Grosfield",
      "Howard Hoover",
      "Joris Jarsky",
      "Matthew MacFadzean",
      "Stephanie Anne Mills",
      "Conrad Pla",
      "Peter Williams",
      "Carleigh Beverly",
      "Kris Bratton",
      "Robin Br청l챕",
      "Landy Cannon",
      "Shane Daly",
      "Carson Durven",
      "Michael Fawkes",
      "Kim Huffman",
      "Amanda Lisman",
      "Sara Mitich",
      "Christopher Russell",
      "Anthony Ulc",
      "Marty Adams",
      "Ron Benjamin",
      "Sharmila Dey",
      "Corrine Koslo",
      "Teresa Pavlinek",
      "Lukas Penar",
      "William Poulin",
      "Danny Smith",
      "Jeffrey R. Smith",
      "Dale Yim",
      "Richard Zwic",
      "Ali Badshah",
      "Shanda Bezic",
      "Carlyn Burchell",
      "Alexandra Castillo",
      "Richard Clarkin",
      "Pablo Coffey",
      "Michael Dyson",
      "Brian Frank",
      "Jonathan Keltz",
      "Patrick Stevenson",
      "Dru Viergever",
      "Genelle Williams",
      "Nigel Shawn Williams",
      "Olunike Adeliyi",
      "Brad Austin",
      "Milton Barnes",
      "Emily Bartlett",
      "Brian Christopher",
      "James Collins",
      "Chris Gillett",
      "Brendee Green",
      "Eli Ham",
      "Michael Kinney",
      "Kevin MacDonald",
      "Katie Messina",
      "Alex Appel",
      "Corinne Conley",
      "Von Flores",
      "Hiro Kanagawa",
      "Gigi Lazzarato",
      "Carolyne Maraghi",
      "Moses Nyarko",
      "Laara Sadiq",
      "Anthony Sherwood",
      "Claire Alan",
      "Lorry Ayers",
      "Jason Blicker",
      "Caleb Cosman",
      "Zarrin Darnell-Martin",
      "Marco Grazzini",
      "Andrew Jackson",
      "Brian Paul",
      "Kalinka Petrie",
      "Rebecca Roberts",
      "Scott Wickware",
      "Glen Anthony",
      "Salvatore Antonio",
      "Benjamin Blais",
      "Ralph Chapman",
      "Ian Deakin",
      "Robert Dodds",
      "Balford Gordon",
      "Michael Holtz",
      "Cory Lee",
      "Peter Prystanski",
      "Mark Robinson",
      "Kresimir Bosiljevac",
      "Steve Comilang",
      "Erica Cox",
      "John Healy",
      "Laura Jeanes",
      "Alisha Morrison",
      "Stephen Park",
      "Tracy Shreve",
      "Adam Chuckryk",
      "William Colgate",
      "Carlos Diaz",
      "Todd Hofley",
      "Grace Lynn Kung",
      "Bill Lake",
      "Jack Langedijk",
      "Larry Mannell",
      "Maxwell McCabe-Lokos",
      "Rena Polley",
      "David Richmond-Peck",
      "Michael Ayres",
      "Trevor Hayes",
      "Paquito 'Paco' Hernaci",
      "Melissa Hood",
      "Martin Julien",
      "David Keeley",
      "Hamish McEwan",
      "Leyla Naghizada",
      "Alex Spencer",
      "Mike Tyrell",
      "Jonathan Watton",
      "Chantelle Chung",
      "Michelle Danese",
      "Cosette Derome",
      "Odeen Eccleston",
      "Wendii Fulford",
      "Sebastien Heins",
      "Trenna Keating",
      "Robert B. Kennedy",
      "Ron Kennell",
      "Mairtin O'Carrigan",
      "Jenny Raven",
      "Jake Simons",
      "Eric Woolfe",
      "Caroline Aked",
      "Rebecca Amare",
      "Woon-Ngor Ballik",
      "Warren Belle",
      "Conrad Bergschneider",
      "Mark Fry",
      "Diego Fuentes",
      "Dennis Mirkovic",
      "Jana Peck",
      "Allan Price",
      "Drew Zeran",
      "Shannon Barnett",
      "Bruce Beaton",
      "Alexander Broughton",
      "Diane Johnstone",
      "Matt MacDonald",
      "Jane Moffat",
      "June Ng",
      "Karan Oberoi",
      "Jay Ould",
      "Saad Siddiqui",
      "Taylor Trowbridge",
      "Rachael Ancheril",
      "Johnie Chase",
      "Daryl Collison",
      "Dean Copkov",
      "Isaiah-Marcus Grant",
      "Audra Yulanda Gray",
      "Wendy Lyon",
      "Misha Rasaiah",
      "Simon Reynolds",
      "Sabryn Rock",
      "Char Sanda Wall",
      "Sean Bell",
      "Katie Bergin",
      "Robin Black",
      "Michael Boisvert",
      "Jason Gosbee",
      "Nikki Grant",
      "Danijel Mandic",
      "Jorge Molina",
      "Tetiana Ostapowych",
      "Geoffrey Antoine",
      "Katherine Ashby",
      "Bridget Graham",
      "David Patrick Green",
      "Chris Handfield",
      "Kevin K. James",
      "Marvin Kaye",
      "Tim MacLean",
      "Jillian Rees-Brown",
      "Ivan Sherry",
      "Justin Tensen",
      "Desmond Campbell",
      "Patrick Garrow",
      "Karen Glave",
      "Lyndie Greenwood",
      "Jody Hewston",
      "Darrin Maharaj",
      "Katie Odegaard",
      "John Paul Ruttan",
      "Tre Smith",
      "Timm Zemanek",
      "Ricardo Betancourt",
      "Ryan Boyko",
      "Laura Carswell",
      "Monica Dottor",
      "Sara Farb",
      "Daniel Karasik",
      "Huse Madhavji",
      "Bola Olubowale",
      "Rob Ramsay",
      "Jonathan Whittaker",
      "Brianna Bisson",
      "Gavin Fox",
      "Jasmin Geljo",
      "David Gingrich",
      "Ken Gorin",
      "Janick Hebert",
      "Matt Hopkins",
      "Inessa Frantowski",
      "Jessica Greco",
      "John Fitzgerald Jay",
      "Molly Kidder",
      "Gianni Luminati",
      "Farah Merani",
      "Sarah Podemski",
      "John Ramdeen",
      "A. Frank Ruffo",
      "Ana Alic",
      "Mackenzie Ball",
      "Makenna Beatty",
      "Darla Biccum",
      "Neil Foster",
      "David Gale",
      "Alvin Leung",
      "Rachel Sellan",
      "Spike Adamson",
      "Brandon Bally",
      "Jimmy Byron",
      "Nick Canakis",
      "Roop Gill",
      "Benjamin Charles Watson",
      "Christine Aziz",
      "John Balabik",
      "Christopher Lee Clements",
      "Ami Heller",
      "Megan Hutchings",
      "Kofi Payton",
      "John Cleland",
      "John Connolly",
      "Lara Kelly",
      "Billy Otis",
      "Daniel Park",
      "David Petrie",
      "Sherry Schell",
      "Bishop Brigante",
      "Michael Brown",
      "Rothaford Gray",
      "Howard Green",
      "Tony Nappo",
      "Alex Sims",
      "Chris Violette",
      "Claudio Aprile",
      "Kira Guloien",
      "Shafin Karim",
      "Richard Walters",
      "Daniel Cook",
      "Gail Roberts",
      "Trevor Coll",
      "Ian Downie",
      "Beatrice Stucki",
      "Paul De La Rosa",
      "Glen Grant",
      "Micah Nelson",
      "Jacob Richter",
      "Paul Braunstein",
      "David Bronfman",
      "Katherine Cleland",
      "Marie-Jos챕e Colburn",
      "Angelique Lewis",
      "Andrew Musselman",
      "Nicolette Pearse",
      "Paskal Vaklev",
      "Corwin Hall",
      "Philippe Buckland",
      "Lorne Hunter",
      "Izaak Smith",
      "Bianca Beauchemin",
      "Darryl Flatman",
      "Martin Roach",
      "Stephen Simpson",
      "Joshua Teixeira",
      "Bruno Verdoni",
      "Michael Daniel Murphy",
      "Christopher Tai",
      "Marco Timpano",
      "Krista Hovsepian",
      "Jung-Yul Kim",
      "Byron Abalos",
      "James Bilik",
      "Ian Matthews",
      "Liam Moore",
      "Sharon Brown",
      "Craig Pike",
      "Lauren Toyota",
      "Antonio Albino",
      "Heather Allin",
      "Sam Malkin",
      "Kojo Mayne",
      "Malachi Brown-Feare",
      "Stephan Dubeau",
      "Adrienne Chan",
      "Al McFoster",
      "Caroline Torti",
      "Kawa Ada",
      "Dorothy Atabong",
      "Ryan Bonneville",
      "Torquil Colbo",
      "Pip Dwyer",
      "Hal Eisen",
      "Shailene Garnett",
      "Michelle Giroux",
      "Steven A. Harvey",
      "Natalia Jonas",
      "Andy McQueen",
      "Andrew Martin Priestman",
      "Diana Salvatore",
      "Nathaniel Sturge",
      "Rami Taha",
      "Vitalie Ursu",
      "Jerry A. Ziler",
      "Darrell Hicks",
      "Christopher Huron",
      "Sherton Sanderson",
      "Shant Srabian",
      "Jamie Ferenczi",
      "Derek Herd",
      "Annie Clark",
      "Roger Doche",
      "Jonathan Hagey",
      "Mackenzie Kerfoot",
      "Chris Lightfoot",
      "Keeva Lynk",
      "Jacquie Neville",
      "Marc Andrew Smith",
      "Emily Alatalo",
      "Hayley Andoff",
      "Lucas Boron",
      "Natalie Dale",
      "Sedina Fiati",
      "Kyle Limkilde",
      "Ariel Lukane",
      "Kathy Maloney",
      "Ryan Massey",
      "Karen O'Keefe",
      "Vasilios Pappas",
      "Lindsay Owen Pierre",
      "Christian Poole",
      "Michael Alexander Robinson",
      "Sam Rosenthal",
      "Clarke Smith",
      "Craig Stickland",
      "Joe Vercillo",
      "Adrian Walters",
      "Chuck Willcocks",
      "Carolina Bartczak",
      "Maria Dinn",
      "Azra Valani",
      "Gibran Hassan"
    ],
    "episode": [
      "6f104d70-e79a-11e9-bb09-cd860116bbdb",
      "70c06e70-e79a-11e9-bb09-cd860116bbdb",
      "70c06e71-e79a-11e9-bb09-cd860116bbdb",
      "70c06e72-e79a-11e9-bb09-cd860116bbdb",
      "70c06e73-e79a-11e9-bb09-cd860116bbdb"
    ]
  },
  "tt1703925": {
    "type": "TV Series",
    "title": "Wilfred",
    "year": "2011",
    "synopsis": "The story of a depressed man who inexplicably is the only one who can see his neighbor's dog as a full grown man in a dog suit.",
    "genres": [
      "Comedy",
      "Drama",
      "Mystery"
    ],
    "thumb_url": "https://m.media-amazon.com/images/M/MV5BMTUxMTk4NDIyMV5BMl5BanBnXkFtZTgwMDQ0MTAyMjE@._V1_SX89_AL_.jpg",
    "rating": "7.8",
    "directors": [
      "Randall Einhorn",
      "Victor Nelli Jr."
    ],
    "actors": [
      "Elijah Wood",
      "Jason Gann",
      "Fiona Gubelmann",
      "Dorian Brown Pham",
      "Chris Klein",
      "Allison Mack",
      "Rodney To",
      "Gerry Bednob",
      "James Remar",
      "Mary Steenburgen",
      "John Michael Higgins",
      "Rob Riggle",
      "Randee Heller",
      "Dwight Yoakam",
      "Nestor Carbonell",
      "Kristen Schaal",
      "Harriet Sansom Harris",
      "Mimi Rogers",
      "Steven Weber",
      "J.P. Manoux",
      "Francesca P. Roberts",
      "Brian Michael Jones",
      "Amanda Troop",
      "Ethan Suplee",
      "Julie Hagerty",
      "Eugene Byrd",
      "Charles Esten",
      "K.T. Thangavelu",
      "E.J. Callahan",
      "Kari Coleman",
      "Kyle Davis",
      "Ellia English",
      "George Coe",
      "Matt Riedy",
      "Chip Chinery",
      "Diane Robin",
      "Mark Newsom",
      "Bob Gunton",
      "Angela Kinsey",
      "Rashida Jones",
      "Jane Kaczmarek",
      "Peter Stormare",
      "Troy Daniel Smith",
      "Robin Williams",
      "Jenny Mollen",
      "William Baldwin",
      "Ed Helms",
      "Damon Herriman",
      "Jeff Holman",
      "Rhea Perlman",
      "Gibson Bobby Sjobeck",
      "Tom Virtue",
      "Brad Dourif",
      "Michael James Bell",
      "Zachary Knighton",
      "Lance Reddick",
      "Ben Tolpin",
      "Barry Watson",
      "Rutger Hauer",
      "Katherine Disque",
      "Jared Gilmore",
      "Katy Mixon",
      "Gabriella Pession",
      "Rachel Sterling",
      "Gabrielle Wagner",
      "Ray Wise",
      "John Alton",
      "Gil Birmingham",
      "Christian Gutierrez",
      "Don Swayze",
      "Katie Wallack",
      "Gina Gershon",
      "Jim Mahoney",
      "Kyle Mooney",
      "Tess Paras",
      "Alex Weed",
      "Tobin Bell",
      "Tom Gallop",
      "Marlowe Peyton",
      "Lauren Powers",
      "Nikki Hahn",
      "Matt Kaminsky",
      "Keegan-Michael Key",
      "Jennifer Bolton Lee",
      "Al Sapienza",
      "Derick Alexander",
      "Steve Solomon",
      "Ursula Burton",
      "Melanie Jean",
      "Roderick McCarthy",
      "Ryan Mirvis",
      "Leonard Robinson",
      "Vincent M. Ward",
      "Sam Adler",
      "Shawn Gnandt",
      "Carole White",
      "Duncan Bravo",
      "Irene Choi",
      "Wayne Wilderson",
      "Toussaint Banks",
      "Lindsay Caschak",
      "Glenn Herman",
      "Dixie Perkinson",
      "Zack Shires",
      "Will Vought",
      "Sally Ann Brooks",
      "Richard Denni",
      "Tiley Chao",
      "Shane Roney",
      "Jim Jansen",
      "Jennifer Floyd",
      "Olivia Rose Keegan",
      "Roger V. Burton",
      "Maxim Knight",
      "Kevin Symons",
      "Claire Titelman",
      "Chad Morgan",
      "Gwen Van Dam",
      "Brian Baumgartner",
      "Tommy Dickie",
      "Candi Milo",
      "Tom Yi",
      "Danielle Reierson",
      "Alejandra Varela",
      "Joe Childs",
      "Youlanda Davis",
      "Marcus Eckert",
      "Jon Overgaauw",
      "Silvana Philippoussis",
      "Jason Remar",
      "Kaidin Michael Stein",
      "J.B. Abajian",
      "Doby Daenger",
      "Timothy E. Goodwin",
      "Jera Sky",
      "Eric Stoltz",
      "Megan Albertus",
      "Craig Duda",
      "Casey Gutting",
      "Chris Leidecker",
      "Kali Muscle",
      "Parrish",
      "Jimmy Scanlon",
      "Austin Uku",
      "Ashley James",
      "Garrett William Henson",
      "Scott Rosendall",
      "Sandra Rosko"
    ],
    "episode": [
      "72feecc0-e79a-11e9-bb09-cd860116bbdb",
      "74515d60-e79a-11e9-bb09-cd860116bbdb",
      "74515d61-e79a-11e9-bb09-cd860116bbdb",
      "74515d62-e79a-11e9-bb09-cd860116bbdb",
      "74515d63-e79a-11e9-bb09-cd860116bbdb"
    ]
  },
  "tt2084970": {
    "type": "Movie",
    "title": "The Imitation Game",
    "year": "2014",
    "synopsis": "During World War II, the English mathematical genius Alan Turing tries to crack the German Enigma code with help from fellow mathematicians.",
    "genres": [
      "Biography",
      "Drama",
      "Thriller"
    ],
    "thumb_url": "https://m.media-amazon.com/images/M/MV5BOTgwMzFiMWYtZDhlNS00ODNkLWJiODAtZDVhNzgyNzJhYjQ4L2ltYWdlXkEyXkFqcGdeQXVyNzEzOTYxNTQ@._V1_SX89_AL_.jpg",
    "rating": "8",
    "directors": [
      "Morten Tyldum"
    ],
    "actors": [
      "Benedict Cumberbatch",
      "Keira Knightley",
      "Matthew Goode",
      "Rory Kinnear",
      "Allen Leech",
      "Matthew Beard",
      "Charles Dance",
      "Mark Strong",
      "James Northcote",
      "Tom Goodman-Hill",
      "Steven Waddington",
      "Ilan Goodman",
      "Jack Tarlton",
      "Alex Lawther",
      "Jack Bannon",
      "Tuppence Middleton",
      "Dominic Charman",
      "James G. Nunn",
      "Charlie Manton",
      "David Charkham",
      "Victoria Wicks",
      "Andrew Havill",
      "Laurence Kennedy",
      "Tim van Eyken",
      "Will Bowden",
      "Miranda Bell",
      "Tim Steed",
      "Peter Agnelli",
      "Lee Asquith-Coe",
      "Hayley Joanne Bacon",
      "Lauren Beacham",
      "Ingrid Benussi",
      "Nicholas Blatt",
      "Carmen Coupeau Borras",
      "Jack Brash",
      "Ancuta Breaban",
      "Heather Broderick",
      "Alex Corbet Burcher",
      "Grace Calder",
      "Richard Campbell",
      "Daniel Chapple",
      "Winston Churchill",
      "Lisa Colquhoun",
      "Alexander Cooper",
      "Chris Cowlin",
      "Kirsty-Marie Day",
      "Leigh Dent",
      "Esther Eden",
      "Sam Exley",
      "Ben Farrow",
      "Iulia Filipovscaia",
      "Mike Firth",
      "Hannah Flynn",
      "James Gard",
      "Guna Gultniece",
      "Adolf Hitler",
      "Leigh Holland",
      "Luke Hope",
      "Vera Horton",
      "Ashley Hudson",
      "Michael John-Lewis",
      "Denis Khoroshko",
      "Debra Leigh-Taylor",
      "Stuart Matthews",
      "Amber-Rose May",
      "Arnold Montey",
      "Samantha Moran",
      "Gina Morrish",
      "Adam Nowell",
      "Joseph Oliveira",
      "Ryan Parker",
      "John Redman",
      "Julio Romeo",
      "Adam Scown",
      "Scott Stevenson",
      "Harry S. Truman",
      "Emilia Ufir",
      "Mark Underwood",
      "Nicola-Jayne Wells",
      "Josh Wichard"
    ]
  }
};
let http=require("http");

class Meta{
  getSeriesByKeyword(type,keyword){
    let result = {};
    for (let id in s){
      if(s[id].hasOwnProperty(type)){
        if (s[id][type].toLowerCase().includes(keyword.toLowerCase()))
          result[id] = s[id];
      }
    }
    return result;
  }
  getDataForDetailPage(id){
    let seriseInfo=s[id]; 
    if(!seriseInfo)
      return null;

    if(seriseInfo.hasOwnProperty("episode")){
      let epiList=new Array();
      for(let i in seriseInfo.episode){
        let id=seriseInfo.episode[i];
        let item=e[id];
        item.id=id;
        epiList.push(item);
      }
      seriseInfo.episode=epiList;
    }
    return seriseInfo;
  }
  getData(url){
    return new Promise(function(resolve,reject){
      let req=http.get(url,function(response){
        let body = "";
        response.on('data', function(data) {
          body+=data;
        });
        response.on('end', function() {
          resolve(body);
        });
      });
      req.end();
    });
  }
	getSeriesAll(){
		return s;
	}
	getSeries(id){
		return s[id];
	}
	getEpsAll(){
		return e;
	}
	getEps(id){
		return s[id]['episode'];
	}
	getDetailOfEp(id){
		return e[id];
	}
}

module.exports =new Meta()